apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: demo-service
spec:
  selector:
    app: Myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  type: ClusterIP

#   apiVersion: Specifies the version of the Kubernetes API.
# kind: Specifies the type of resource being created (in this case, a Service).
# metadata: Provides metadata about the Service, including its name and labels.
# spec: Specifies the desired state of the Service.
# selector: Defines how the Service should find the Pods it routes traffic to. In this case, it selects Pods with the label app: demo.
# ports: Specifies the port configuration for the Service.
# protocol: The protocol used by the Service (TCP).
# port: The port on which the Service will be exposed.
# targetPort: The port on the Pod that the traffic will be directed to.
# type: Specifies the type of Service. ClusterIP exposes the Service on a cluster-internal IP.
